# -*- coding: utf-8 -*-

OPENING_HOURS_TEST_DATA = [
    {'nonstop': True, 'mo_o': None, 'tu_o': None, 'we_o': None, 'th_o': None, 'fr_o': None, 'sa_o': None,
     'su_o': None, 'mo_c': None, 'tu_c': None, 'we_c': None, 'th_c': None, 'fr_c': None, 'sa_c': None,
     'su_c': None, 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None, 'processed': '24/7'},
    {'nonstop': None, 'mo_o': None, 'tu_o': None, 'we_o': None, 'th_o': None, 'fr_o': None, 'sa_o': None,
     'su_o': None, 'mo_c': None, 'tu_c': None, 'we_c': None, 'th_c': None, 'fr_c': None, 'sa_c': None,
     'su_c': None, 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None, 'processed': None},
    {'nonstop': False, 'mo_o': None, 'tu_o': None, 'we_o': None, 'th_o': None, 'fr_o': None, 'sa_o': None,
     'su_o': None, 'mo_c': None, 'tu_c': None, 'we_c': None, 'th_c': None, 'fr_c': None, 'sa_c': None,
     'su_c': None, 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None, 'processed': None},
    {'nonstop': None, 'mo_o': '08:00', 'tu_o': '10:00', 'we_o': '11:00', 'th_o': '08:00', 'fr_o': '08:00',
     'sa_o': '11:20',
     'su_o': None, 'mo_c': '16:00', 'tu_c': '18:00', 'we_c': '14:00', 'th_c': '18:00', 'fr_c': '14:00',
     'sa_c': '14:00',
     'su_c': None, 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None,
     'processed': 'Mo 08:00-16:00; Tu 10:00-18:00; We 11:00-14:00; Th 08:00-18:00; Fr 08:00-14:00; Sa 11:20-14:00'},
    {'nonstop': None, 'mo_o': '08:00', 'tu_o': '08:00', 'we_o': '08:00', 'th_o': '10:00', 'fr_o': '10:00',
     'sa_o': '11:20',
     'su_o': '11:20', 'mo_c': '16:00', 'tu_c': '16:00', 'we_c': '16:00', 'th_c': '18:00', 'fr_c': '14:00',
     'sa_c': '14:00',
     'su_c': '14:00', 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None,
     'processed': 'Mo-We 08:00-16:00; Th 10:00-18:00; Fr 10:00-14:00; Sa-Su 11:20-14:00'},
    {'nonstop': None, 'mo_o': '08:00', 'tu_o': '10:00', 'we_o': '08:00', 'th_o': '10:00', 'fr_o': '10:00',
     'sa_o': '11:20',
     'su_o': '08:00', 'mo_c': '16:00', 'tu_c': '16:00', 'we_c': '16:00', 'th_c': '16:00', 'fr_c': '16:00',
     'sa_c': '16:00',
     'su_c': '16:00', 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None,
     'processed': 'Mo,We,Su 08:00-16:00; Tu,Th,Fr 10:00-16:00; Sa 11:20-16:00'},
    {'nonstop': None, 'mo_o': '08:00', 'tu_o': '09:00', 'we_o': '09:00', 'th_o': '10:00', 'fr_o': '10:00',
     'sa_o': '11:20',
     'su_o': '08:00', 'mo_c': '16:00', 'tu_c': '16:00', 'we_c': '16:00', 'th_c': '16:00', 'fr_c': '16:00',
     'sa_c': '16:00',
     'su_c': '16:00', 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': None, 'lunch_break_stop': None,
     'processed': 'Mo,Su 08:00-16:00; Tu-We 09:00-16:00; Th-Fr 10:00-16:00; Sa 11:20-16:00'},
    {'nonstop': None, 'mo_o': '08:00', 'tu_o': '09:00', 'we_o': '09:00', 'th_o': '10:00', 'fr_o': '10:00',
     'sa_o': '11:20',
     'su_o': '08:00', 'mo_c': '16:00', 'tu_c': '16:00', 'we_c': '16:00', 'th_c': '16:00', 'fr_c': '16:00',
     'sa_c': '16:00',
     'su_c': '16:00', 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': '12:00', 'lunch_break_stop': '12:30',
     'processed': 'Mo,Su 08:00-12:00,12:30-16:00; Tu-We 09:00-12:00,12:30-16:00; Th-Fr 10:00-12:00,12:30-16:00; Sa 11:20-12:00,12:30-16:00'},
    {'nonstop': None, 'mo_o': '08:00', 'tu_o': '09:00', 'we_o': '09:00', 'th_o': '09:00', 'fr_o': '10:00',
     'sa_o': '10:00',
     'su_o': '10:00', 'mo_c': '16:00', 'tu_c': '16:00', 'we_c': '16:00', 'th_c': '16:00', 'fr_c': '16:00',
     'sa_c': '16:00',
     'su_c': '16:00', 'summer_mo_o': None, 'summer_tu_o': None, 'summer_we_o': None, 'summer_th_o': None,
     'summer_fr_o': None, 'summer_sa_o': None, 'summer_su_o': None, 'summer_mo_c': None, 'summer_tu_c': None,
     'summer_we_c': None, 'summer_th_c': None, 'summer_fr_c': None, 'summer_sa_c': None, 'summer_su_c': None,
     'lunch_break_start': '12:00', 'lunch_break_stop': '12:30',
     'processed': 'Mo 08:00-12:00,12:30-16:00; Tu-Th 09:00-12:00,12:30-16:00; Fr-Su 10:00-12:00,12:30-16:00'},
]
