image: python:3.9

variables:
  PYTHONPATH: `dirname $(realpath $0)`

before_script:
  - pip3 install -r requirements.txt
stages:
  - test

unit_tests:
  stage: test
  script:
    - python3 ${PYTHONPATH}/test/test_create_db.py
