language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: true

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install --pre -r requirements.txt"

env:
  - PYTHONPATH= `dirname $(realpath $0)`

# command to run test
script:
  - python3 ${PYTHONPATH}/test/test_create_db.py
