language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: true

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install --pre -r requirements.txt"

# command to run test
script:
  - python test_create_db.py

