# OSM POI Matchmaker
version: "2.2"
volumes:
  opm_dbdata:
  opm_osmdata:
  opm_outputdata:
services:
  db:
    image: postgis/postgis:17-3.5
    container_name: opm_db
    environment:
      - POSTGRES_USER=poi
      - POSTGRES_PASSWORD=poitest
      - POSTGRES_DB=poi
    ports:
      - "15432:5432"
    shm_size: 1G
    volumes:
      #- ../container/dbdata-9.6-2.5:/var/lib/postgresql/data/
      # - ../container/dbdata-9.6:/var/lib/postgresql/data/
      - ../container/dbdata-fresh:/var/lib/postgresql/data/
      # - ${PWD}/osm2pgsql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    restart: on-failure
    oom_score_adj: -100
  osm_load_app:
    image: osm_loader:latest
    container_name: opm_osm_load_app
    environment:
      - PGPASSWORD=poitest
      - OSM2PGSQL_VERSION=1.6.0
    volumes:
      - ../container/osmdata:/opm/osm
    depends_on:
      - db
    links:
      - db
    restart: on-failure
    oom_score_adj: -100
    mem_limit: 4g
  poi_load_app:
    image: osm_poi_matchmaker:latest
    container_name: opm_poi_load_app
    volumes:
      - ../container/osmdata:/opm/osm
      - ../container/importdata:/opm/osm_poi_matchmaker/output
      - ../container/downloaddata:/opm/osm_poi_matchmaker/cache_url
    depends_on:
      - db
    restart: on-failure
    oom_score_adj: -100
    mem_limit: 4g
    cap_add:
      - SYS_PTRACE
    pid: host
