name: Run tests

on: [push, pull_request]

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
    run-tests:
        name: Run unit tests

        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up latest python3.11
          uses: actions/setup-python@v5
          with:
              python-version: "3.11.x"

        - name: Install dependencies
          run: |
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
              
        - name: Run the tests
          run: |
            python3 ${PYTHONPATH}/test/test_create_db.py
